language: go
go:
    - 1.5
    - 1.6
    - tip

matrix:
    fast_finish: true

before_install:
    - go get golang.org/x/tools/cmd/vet
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint
    - go get github.com/mattn/goveralls

script:
    - make vet lint generate test
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
