dist: xenial
language: go
go: '1.11'
python: '3.6'
services:
- docker
go_import_path: go.mozilla.org/autograph

before_install:
- make install-dev-deps
- sudo apt-get update
- sudo apt-get install python3 python3-pip

script:
- make generate lint vet install
- make dummy-statsd &
- make build-container
- make test-container-ci
- goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

# Run a synthetic monitoring test against the container
- make run-container

- cd $GOPATH/src/go.mozilla.org/autograph/tools/autograph-monitor && make && ./autograph-monitor

# Sign an add-on
- |
    wget https://addons.mozilla.org/firefox/downloads/file/935711/pomodoro_clock-1.1.1-an+fx-windows.xpi && \
    cd $GOPATH/src/go.mozilla.org/autograph/tools/autograph-client && \
    CONFIG=ci SIGNER_ID=webextensions-rsa HAWK_USER=alice HAWK_SECRET=fs5wgcer9qj819kfptdlp8gm227ewxnzvsuj9ztycsx08hfhzu CN="testaddon@allizom" ./build_test_xpis.sh pomodoro_clock-1.1.1-an+fx-windows.xpi
