version: "3"
volumes:
  tmpdir:
services:
  db:
    container_name: autograph-db
    image: autograph:db
    build:
      context: database/
    environment:
      - POSTGRES_DB=autograph
    ports:
      - "5432:5432"
    command: postgres -c 'ssl=on' -c 'ssl_cert_file=/opt/server.crt' -c 'ssl_key_file=/opt/server.key'

  app:
    container_name: autograph-app
    image: autograph-app
    build:
      context: .
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__heartbeat__"]
      interval: 60s
      timeout: 10s
      retries: 3

  app-hsm:
    container_name: autograph-app-hsm
    image: autograph-app-hsm
    build:
      context: tools/softhsm/
    environment:
      - AUTOGRAPH_DB_DSN=host=db user=myautographdbuser dbname=autograph password=myautographdbpassword sslmode=verify-full sslrootcert=/opt/db-root.crt
    links:
      - db
    ports:
      - "8001:8001"
    volumes:
      - tmpdir:/tmp/
    command:
      [
        "/app/wait-for-it.sh",
        "db:5432",
        "--",
        "autograph",
        "-c",
        "/app/autograph.softhsm.yaml",
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/__heartbeat__"]
      interval: 60s
      timeout: 10s
      retries: 3

  monitor:
    container_name: autograph-monitor
    image: autograph-monitor
    build:
      context: tools/autograph-monitor/
    environment:
      - AUTOGRAPH_URL=http://autograph-app:8000/
    links:
      - app
    volumes:
      - tmpdir:/tmp/
    command:
      [
        "/app/wait-for-it.sh",
        "autograph-app:8001",
        "--",
        "/go/bin/autograph-monitor",
      ]

  monitor-hsm:
    container_name: autograph-monitor-hsm
    image: autograph-monitor
    build:
      context: tools/autograph-monitor/
    environment:
      - AUTOGRAPH_URL=http://autograph-app-hsm:8001/
    links:
      - app-hsm
    volumes:
      - tmpdir:/tmp/
    command:
      [
        "/app/wait-for-it.sh",
        "autograph-app-hsm:8001",
        "--",
        "/app/run-monitor-with-root-hash.sh",
        "/tmp/autograph.softhsm.yaml",
        "normandy",
      ]
